# application.yml

# 매퍼 경로 설정
mybatis:
  mapper-locations:
    - classpath:org/hj/mapper/sub/*Mapper.xml
    - classpath:org/hj/mapper/pub/*Mapper.xml


# 서버 설정
server:
  port: 8080  # 서버가 실행될 포트 번호

# 스프링 프로파일 설정
spring:
  profiles:
    active: dev  # 활성화할 프로파일

# 데이터베이스 설정 - sub 데이터베이스
sub:
  datasource:
    url: jdbc:mysql://192.168.30.181:3306/Supplier
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000

# 데이터베이스 설정 - pub 데이터베이스
pub:
  datasource:
    url: jdbc:mysql://192.168.30.181:3306/public_schema
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000


